### PR TITLE
Updates to normalize()

### PR DESCRIPTION
**Pull request by kfkaplan**
Updates to the definition normalize for EchelleSpectrum and EchelleSpectrumList. 

 Fixed an issue where user was unable to specify the the order in EchelleSpectrumList to normalize all the orders to (it would default to order 0 and the argument didn't match the variable used to index the orders).

 Made it so median_flux can be passed to EchelleSpectrum when EchelleSpectrumList is called.

EchelleSpectrumList.normalize() now calls EchelleSpectrum.normalize() per order (allows error propagation, ect.) instead of doing just a divide.

### CODE REVIEW

**Comment by kfkaplan** [comment]
Committed some more changes.  Added definition combine_lists() to utilities.py which allows you to combine two echelle lists into one.  Mainly created it so I can combine the IGRINS H and K bands into one object.

Also added flatten() to EchelleSpectrumList.

**Comment by gully** [comment]
Cool stuff! Thanks for opening the pull request.  I'll review it now.

**Comment by gully** [comment]
Thanks again! Some things that pop into my mind:

### Normalize
The naming of the `median_flux=` kwarg may be misleading: `median_flux=17.1` does not produce a flux vector that has a median flux of 17.1, correct?  So maybe we should rename the kwarg to `normalize_by=` or equivalent.  

It appears the typical pattern here would be something like:
```python
median_flux = np.nanmedian(spec_list[13].flux)
result = spec_list.normalize(median_flux=median_flux)
```

Previously we could have used divide, but that wouldn't apply the "band math" to the ancillary spectra:
```python
median_flux = np.nanmedian(spec_list[13].flux)
result = spec_list.divide(median_flux, handle_meta='first_found')
```

That makes me wonder if we should expand the "band math" to check for ancillary spectra, and if present to apply the math operator (add, divide, subtract, multiply) to the ancillary spectra too.

**Comment by gully** [comment]
### Combine list
Indeed we would like to have better support for operating on the IGRINS H and K bands simultaneously, so your `combine_list` contribution is a step in the right direction.  I have uploaded the K-band counterpart to the H-band data in the [muler example data](https://github.com/OttoStruve/muler_example_data) repository, so we can now make tutorials demonstrating this use case more easily.

Some thoughts here:

We currently use the word "combine" when refering to methods that co-add spectra.  The term works linguistically for both scenarios (co-adding and appending), but the ambiguity may confuse newcomers, so we seek a disambiguation.  We can either rebrand "combine" to "coadd" or  change this "combine list" to "append list" or "concatenate list".  My inclination is the latter, but I'm open to hearing arguments for or against.

My gut instinct when I saw your implementation of `combine_list` was that it should work with just a `output = list1 + list2`, the same way as adding lists in Python. But it doesn't.  The reason is that we have over-ridden the band math `add` for SpectrumList-like objects:

```python
from specutils import SpectrumList

# spec_list and spec_list2 are IGRINSSpectrumList objects for H and K bands
spec_list_base1 = SpectrumList(spec_list)
spec_list_base2 = SpectrumList(spec_list2)

len(spec_list_base1), len(spec_list_base2)
> (28, 26)

out = spec_list_base1 + spec_list_base2
len(out)
> 54

# Does not work!
spec_list + spec_list2
> "Can only apply 'add' function to quantities with compatible dimensions"
```

So I think we should revisit the bandmath with some more scrutiny, because it has some bigger consequences than we had realized.  For astronomers, band math may seem natural.  But for Python programmers, list-like objects not concatenating with the `+` operator may seem weird.  For better or worse, we are making a breaking change with Specutils, which means future improvements to the SpectrumList object class may not extend to IGRINSSpectrumList.  So it's worth thinking about.

I think the essence of the question here gets down to when---if at all---the user should apply `.stitch()` to turn the `IGRINSSpectrumList` object into a regular old `IGRINSSpectrum`.  This question is somewhat problem-dependent, since certain instrumental artifacts operate on an order-by-order basis.  An example pattern may therefore be to mitigate those order-dependent issues (de-blazing/normalization type operations), and then stitch.  Then co-adding spectra works just fine.

**Comment by kfkaplan** [comment]
**Renaming median_flux**
I renamed `median_flux` to `normalize_by`.  I agree,  this makes more sense.

**Changing name of combine_list**
I renamed the def in utilities.py from `combine_list` to `concatenate_orders`.  I was also thinking the same thing that the name of this def was a bit confusing.  I think this new name is much more clear on its purpose.  I actually didn't realize `extend` works, and wonder if we even need `concatenate_orders` now, but it does wrap in `copy.deepcopy` so makes for cleaner scripts and preserves how muler returns the resulting spectrum when running a def.   There is no harm in leaving it and the user can use `concatenate_orders` or `extend` as they see fit, but let me know what you think.

**Extending functionality of EchelleSpectrumList and **
I think, as much as feasibility possible, we should extend the functionality of `Spectrum1D` from specutils to `EchelleSpectrum` and extend what can be done with `EchelleSpectrum` to  `EchelleSpectrumList`, including the band math.  This gives the user the maximum flexibility in choosing how to process their spectra, allowing them to use the same methods whether or not orders are stitched together.  I personally prefer to do most of my processing on an order-by-order basis and then combine the final result into a single spectrum.

**Ancillary Spectra**
I actually just realized this was a variable.  What was the intent with ancillary spectra?  Was the idea that any changes made to the main spectrum also apply to ancillary spectra?  I think we should be consistent with whatever we do here.  If one def applies to ancillary spectra along with the main spectrum, all defs should apply.  This seems like a bit of work to implement, however.

**Comment by kfkaplan** [comment]
Some minor updates but the big one is I automated finding "yhi" when running plot().  Much nicer to have the y-axis automatically scale.

**Comment by gully** [comment]
Ok, thanks for these changes and good discussions here.  

Enough has changed here that we need to consider whether these backwards breaking changes will derail existing users.  I think mostly the changes are safe, but I'll spot-check to be sure.  Some folks are beginning to rely on muler for research projects and if it changes too dramatically without a warning they 1) get mad, or 2) may freeze projects at old versions of muler, bifurcating the user base to the old-school and the new-school.  We want to avoid both of these forms of sadness.

One good way to hedge against those changes is to make unit tests for common patterns that should always produce the same result.

**Comment by kfkaplan** [comment]
Yeah we definitely need to be careful on how we merge with the main branch.  I don't think any of these changes would affect anyone, but I don't know.  For example, someone's code might rely on the IGRINS orders being in a specific order and reversing it, even if sorting the orders by wavelength makes sense to me, could cause someone's pipeline to break.

I also want to avoid bifurcating things the other way, where I have my own branch that becomes further and further disconnected from the main branch.  A lot of these changes are done so I can move forward with my own research, so I will continue to have them accumulate in some branch or another.

As for unit tests, what exactly are we going for?
The existing tests seem to do a good job checking that the code works.
It would make sense to have a set of analytical tests, like measure the EW of a line, find the minimum and maximum wavelength in a spectrum, ect.  Could these be worked into the "tests"?

**Comment by gully** [comment]
Ok, finally coming back to this, sorry for the delay.  There are a few other inter-related PR's so I'm hoping we don't hit too many merge conflicts as we start merging these...

**Pull request merged**
